name: ppstm

channels:
  - conda-forge
  - defaults

dependencies:
  - gxx=15.2.0
  - make=4.4.1
  - python=3.14.5
  - numpy=2.4.6
  - scipy=1.17.1
  - matplotlib=3.10.9
  - tomli=2.4.1
  - ase=3.28.0  # optional
  - gpaw=25.7.0  # optional
  - pyopencl=2026.1.1  # optional
  - jupyter=1.1.1  # optional
  - pip=26.1.2  # optional
  - pip:
    - ppafm==0.4.0  # optional
