name: ppstm-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - gxx=15.2.0
  - make=4.4.1
  - python=3.12.13
  - numpy=2.4.6
  - scipy=1.17.1
  - matplotlib=3.10.9
  - tomli=2.4.1
  - pytest=9.0.3
  - pytest-cov=7.1.0  # optional
  - ase=3.28.0  # optional
  - gpaw=25.7.0  # optional
  - pyopencl=2026.1.1  # optional
  - scipy-stubs=1.17.1.5  # optional
  - pandas=3.0.3  # optional
  - pandas-stubs=3.0.3.260530  # optional
  - seaborn=0.13.2  # optional
  - jupyter=1.1.1  # optional
  - pip=26.1.2
  - pip:
    - ppafm==0.4.0

