name: ppstm-mac

channels:
  - conda-forge

dependencies:
  - clangxx_osx-arm64=22.1.8 # clang++-22 necessary for comlilation on MAC
  - llvm-openmp=22.1.8 # clang++-22 necessary for comlilation on MAC
  - make=4.4.1
  - python=3.12.13
  - numpy=2.4.6
  - scipy=1.17.1
  - matplotlib=3.10.9
  - tomli=2.4.1
  - ase=3.28.0  # optional
  - jupyter=1.1.1  # optional
  - pyopencl=2026.1.1  # optional
  - ocl_icd_wrapper_apple=1.0.0  # optional
  - pyqt=5.15.11  # optional
  - pip=26.1.2
  - pip:
    - ppafm==0.4.0
    - torch==2.13.0  # optional
    - gpaw==25.7.0 # optional - not working from conda-forge directly

