from abc import ABC
from functools import partial
from pathlib import Path
from typing import List

import numpy as np
import pytest

from pyPPSTM import STMutils
from pyPPSTM.probe_stm_opencl import ProbeSTMOpenCLParallel
from pyPPSTM.probe_stm_pytorch import ProbeStmPytorch
from pyPPSTM.probe_stm_numpy import ProbeStmNumpy
from tests.didv._test_didv_backend_consistency import _TestDidvBackendConsistencySpdSampleOrbitalsOrbital, \
    _TestDidvBackendConsistencySpSampleOrbitalsOrbital, _TestDidvBackendConsistencySpSampleOrbitals, \
    _TestDidvBackendConsistencySpdSampleOrbitals

# Register assert rewrite BEFORE import to enable better error messages in inherited tests
pytest.register_assert_rewrite("tests.didv._test_didv_backend_consistency")
from tests.didv import _test_didv_backend_consistency


class _TestDidvBackendConsistencyWithRealTipPositions(_test_didv_backend_consistency._TestDidvBackendConsistency, ABC):
    """Backend-consistency tests using tip positions generated by STMutils."""
    _SCAN_WINDOW: List[List[float|int]]
    _SCAN_DIM: List[int]
    _TIP_TYPE = "fixed"
    _PLOT_ATOMS = False

    @pytest.fixture(scope="class")
    def tip_positions_batch(self):
        """Batch of real (STMutils-sourced) tip positions."""
        yield self._batch_all_tip_positions()

    def _sample_tip_positions(self, n_samples: int) -> np.ndarray:
        """Sample tip positions from the full real scan grid without replacement.

        Args:
            n_samples: Number of tip positions to draw.

        Returns:
            Tip positions, shape: (n_samples, 3).

        Raises:
            ValueError: If n_samples exceeds the total number of available positions.
        """
        all_tip_positions = self._batch_all_tip_positions().reshape(-1, 3)

        if n_samples > (max_positions := len(all_tip_positions)):
            raise ValueError(f"Cannot sample {n_samples} positions from {max_positions} available")

        tip_positions_indices = self._make_rng().choice(range(max_positions), size=n_samples, replace=False)
        return all_tip_positions[tip_positions_indices]

    def _batch_all_tip_positions(self) -> np.ndarray:
        """Return the full real tip-position grid generated by STMutils.

        Returns:
            Tip positions, shape: (n_z, n_y, n_x, 3).
        """
        tip_r, tip_r0, lvec, extent, atomic_head_or_info = STMutils.get_tip_positions({
            "scan": {
                "tip_type": self._TIP_TYPE,
                "scan_window": self._SCAN_WINDOW,
                "scan_dim": self._SCAN_DIM,
            },
            "output": {
                "plot_atoms": self._PLOT_ATOMS
            },
        })
        return tip_r


class _TestDidvBackendConsistencyWithRealTipPositionsOrbital(_TestDidvBackendConsistencyWithRealTipPositions, ABC):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions.
    Inspired by examples/orbitals_tests."""
    # Scan parameters: 10 Å × 10 Å × 10 Å volume with 50×50×50 point grid
    _SCAN_WINDOW = [
        [-5, -5, -5],
        [5, 5, 5]
    ]  # Angstroms
    _SCAN_DIM = [50, 50, 50]  # Points per dimension


class TestDidvBackendConsistencyOrbitalWithRealTipPositionsSpdSampleOrbitals(
    _TestDidvBackendConsistencyWithRealTipPositionsOrbital,
    _TestDidvBackendConsistencySpdSampleOrbitalsOrbital):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions
    for s, p and d sample orbitals.
    Inspired by examples/orbitals_tests."""
    pass


class TestDidvBackendConsistencyWithRealTipPositionsSpSampleOrbitalsOrbital(
    _TestDidvBackendConsistencyWithRealTipPositionsOrbital,
    _TestDidvBackendConsistencySpSampleOrbitalsOrbital):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions
    for s and p sample orbitals.
    Inspired by examples/orbitals_tests."""
    pass


class TestDidvBackendConsistencyWithRealTipPositionsSpSampleOrbitals4NCoronene(
    _TestDidvBackendConsistencySpSampleOrbitals,
    _TestDidvBackendConsistencyWithRealTipPositions):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions
    for s and p sample orbitals.
    Inspired by examples/4N-coronene."""
    # Scan parameters: 16 Å × 16 Å × 1 Å volume with 32×32×1 point grid
    _SCAN_WINDOW = [
        [0, 0, 10],
        [16, 16, 11],
    ]  # Angstroms
    _SCAN_DIM = [32, 32, 1]  # Points per dimension

    _V = 1.0  # voltage
    _EIGENENERGIES = np.loadtxt(Path(__file__).parent / "eigenenergies_4n_coronene.csv", delimiter=",")
    _SAMPLE_ATOMS_POSITIONS = np.loadtxt(Path(__file__).parent / "sample_atom_positions_4n_coronene.csv", delimiter=",")
    _LCAO_COEFFICIENTS = np.loadtxt(Path(__file__).parent / "lcao_coefficients_4n_coronene.csv", delimiter=",")


@pytest.mark.slow
class _TestDidvBackendConsistencyWithRealTipPositionsSi7x7(_TestDidvBackendConsistencyWithRealTipPositions, ABC):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions.
    Inspired by examples/Si_7x7."""
    # Scan parameters: 50 Å × 30 Å × 1 Å volume with 100×60×1 point grid
    _SCAN_WINDOW = [
        [-2.0, -15.0, 8.7],
        [48.0, 15.0, 9.7],
    ]  # Angstroms
    _SCAN_DIM = [100, 60, 1]  # Points per dimension

    _V = -2.0  # voltage

    _BACKENDS_NAME_FN_RTOL = (
        ("OpenCL parallel",            ProbeSTMOpenCLParallel.didv,                                      8e-6),
        # ("OpenCL sequential",          ProbeSTMOpenCLSequential.didv,                                    8e-6),  # skip to prevent test-suite state poisoning (#86)
        ("NumPy (default chunking)",   ProbeStmNumpy.didv,                                               8e-6),
        ("PyTorch (default chunking)", ProbeStmPytorch.didv,                                             8e-6),
        ("NumPy (no chunking)",        partial(ProbeStmNumpy.didv,    n_tip_position_chunks=1), 8e-6),
        ("PyTorch (no chunking)",      partial(ProbeStmPytorch.didv,  n_tip_position_chunks=1), 8e-6),
        ("NumPy (2 chunks)",           partial(ProbeStmNumpy.didv,    n_tip_position_chunks=2), 8e-6),
        ("PyTorch (2 chunks)",         partial(ProbeStmPytorch.didv,  n_tip_position_chunks=2), 8e-6),
    )


class TestDidvBackendConsistencyWithRealTipPositionsSpdSampleOrbitalsSi7x7(
    _TestDidvBackendConsistencySpdSampleOrbitals,
    _TestDidvBackendConsistencyWithRealTipPositionsSi7x7):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions
    for s, p and d sample orbitals.
    Inspired by examples/Si_7x7."""
    _EIGENENERGIES = np.loadtxt(Path(__file__).parent / "eigenenergies_si_7x7.csv", delimiter=",")
    _SAMPLE_ATOMS_POSITIONS = np.loadtxt(Path(__file__).parent / "sample_atom_positions_si_7x7.csv", delimiter=",")
    _LCAO_COEFFICIENTS = np.loadtxt(Path(__file__).parent / "lcao_coefficients_si_7x7.csv", delimiter=",")


class TestDidvBackendConsistencyWithRealTipPositionsSpSampleOrbitalsSi7x7(
    _TestDidvBackendConsistencySpSampleOrbitals,
    _TestDidvBackendConsistencyWithRealTipPositionsSi7x7):
    """Tests dI/dV backend consistency with real (STMutils-sourced) tip positions
    for s and p sample orbitals.
    Inspired by examples/Si_7x7."""
    _EIGENENERGIES = np.loadtxt(Path(__file__).parent / "eigenenergies_si_7x7.csv", delimiter=",")
    _SAMPLE_ATOMS_POSITIONS = np.loadtxt(Path(__file__).parent / "sample_atom_positions_si_7x7.csv", delimiter=",")
    _LCAO_COEFFICIENTS = np.loadtxt(Path(__file__).parent / "lcao_coefficients_si_7x7.csv", delimiter=",")\
        .reshape(len(_EIGENENERGIES), len(_SAMPLE_ATOMS_POSITIONS), 9)\
        [..., :4]\
        .reshape(len(_EIGENENERGIES), len(_SAMPLE_ATOMS_POSITIONS)*4)
