title = "Default configuration"


[scan]
scan_type       = 'dIdV'
tip_type        = 'fixed'
scan_window     = [[-5, -5, -5], [5, 5, 5]]
scan_dim        = [50, 50, 50]
V               = -0.04 # -0.04 -s orb and -0.03 are inside 
V_max           =  0.0
dV              =  0.1
eta             =  10
tip_orb         = 's'
sample_orbs     = 'sp'

[input]
path            = './'
dft_code        = 'fireball'
geometry_file   = 'input_plot.xyz'
pbc             = [0, 0]
lvs             = false
spin            = false
cp2k_name       = 'None'
Q               = 0.0
K               = 0.24
data_format     = 'npy'

[advanced]
cut_atoms       = -1
lower_atoms     = []
lower_coefs     = []
work_function   = 5.0
work_function_decay =  0.0
fermi           = 0.0
cut_min         = -0.045 # -0.04 -s orb and -0.03 are inside
cut_max         = -0.025

[output]
plot_atoms      = true
PNG             = false
WSxM            = false
NPY             = false
XSF             = true
